spring:
  application:
    name: common-utils
  data:
    redis:
      # Replace the award IP with your own public IP
      host: localhost
      port: 6379
      password: 'wenhaoge'

rocketmq:
  producer:
    package-bind-op:
      name-server: localhost:9876
      group: 'test-group'
      topic: 'test-topic'
      tag: 'test-tag'
      retry-another-broker-when-not-store-o-k: true
      retry-times-when-send-failed: 3
      send-msg-timeout: 3000
  consumer:
    package-bind-op:
      name-server: localhost:9876
      group: 'test-group'
      topic: 'test-topic'
      tag: 'test-tag'

redis:
  key:
    prefix:
      common-prefix: 'common:utils'
      package-change-msg: 'package:change:msg:key:'