version: '3.8'
services:
  namesrv:
    image: apache/rocketmq:5.3.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    networks:
      - rocketmq
    command: sh mqnamesrv
    volumes:
      - ./conf/plain_acl.json:/opt/rocketmq/conf/plain_acl.json

  broker:
    image: apache/rocketmq:5.3.0
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    depends_on:
      - namesrv
    networks:
      - rocketmq
    command: sh mqbroker -c /opt/rocketmq/conf/broker.conf
    volumes:
      - ./conf/plain_acl.json:/opt/rocketmq/conf/plain_acl.json
      - ./conf/broker.conf:/opt/rocketmq/conf/broker.conf  # 加载Broker配置文件

  proxy:
    image: apache/rocketmq:5.3.0
    container_name: rmqproxy
    networks:
      - rocketmq
    depends_on:
      - broker
      - namesrv
    ports:
      - 8080:8080
      - 8081:8081
    restart: on-failure
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    command: sh mqproxy -pc /opt/rocketmq/conf/plain_acl.json
    volumes:
      - ./conf/plain_acl.json:/opt/rocketmq/conf/plain_acl.json

  dashboard:
    image: apacherocketmq/rocketmq-dashboard:1.0.0
    container_name: rmqdashboard
    networks:
      - rocketmq
    depends_on:
      - namesrv
    ports:
      - 8090:8080
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Drocketmq.dashboard.login.username=yourusername -Drocketmq.dashboard.login.password=yourpassword
    volumes:
      - ./conf/plain_acl.json:/opt/rocketmq/conf/plain_acl.json

networks:
  rocketmq:
    driver: bridge