spring:
  application:
    name: common-utils
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  datasource:
    url: jdbc:mysql://${MYSQL_URL:localhost:3306/common-utils}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: CommonUtilsHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000
      leak-detection-threshold: 15000
  jpa:
    show-sql: true
    open-in-view: false
rocketmq:
  producer:
    package-bind-op:
      name-server: ${ROCKETMQ_PRODUCER_NAME_SERVER:localhost:9876}
      group: ${ROCKETMQ_PRODUCER_GROUP:test-group}
      topic: ${ROCKETMQ_PRODUCER_TOPIC:test-topic}
      tag: ${ROCKETMQ_PRODUCER_TAG:test-tag}
      retry-another-broker-when-not-store-o-k: true
      retry-times-when-send-failed: 3
      send-msg-timeout: 3000
  consumer:
    package-bind-op:
      name-server: ${ROCKETMQ_CONSUMER_NAME_SERVER:localhost:9876}
      group: ${ROCKETMQ_CONSUMER_GROUP:test-group}
      topic: ${ROCKETMQ_CONSUMER_TOPIC:test-topic}
      tag: ${ROCKETMQ_CONSUMER_TAG:test-tag}
redis:
  key:
    prefix:
      common-prefix: 'common:utils:'
      package-change-msg: 'package:change:msg:key:'
      refresh-token-key: 'refresh:token:key:'
      user-jwt-key: 'user:jwt:key:'
jwt:
  refresh-expiration-ms: 2592000000
  secret: ${JWT_SECRET:Ar/5FP7n80Szh0JFlD/iSxTuzHVuIwHhiKiRzISwaFW1ILVMuqZ+gkTVHz8sENINw5DLFLgZ5gXG41EdOYKSXA==}
  expiration-in-ms: 900000
  generate-times: 5